# database for storing punishments and userdata
database:
  type: h2 # h2, MariaDB or MySQL
  url: jdbc:h2:file:./banmod.h2 # default is a local h2 database
  username: sa
  password:

# messaging service for cross-server
messaging-service:
  type: none # 'none', 'polling-db' or 'rabbit-mq'

  # uncomment this example section to use 'polling-db' with a different database
  #database:
  #  type: MariaDB
  #  url: jdbc:mariadb://localhost:3306/banmod_messaging
  #  username: anonymous
  #  password: anonymous
  # you can adjust the polling interval. this will define how long punishments will lag between servers
  #interval: 2s

  # uncomment this example config for 'rabbit-mq'
  #uri: amqp://anonymous:anonymous@localhost:5672/banmod_messaging
