name: LibMod
version: '0.1.0'
author: Kaleidox
description: Compatibility Library for AMPZ Minecraft Addons
website: https://github.com/AMPZNetwork/LibMod
main: com.ampznetwork.libmod.spigot.LibMod$Spigot
default-permission: op
api-version: '1.18'
database: true
load: STARTUP
depend:
  - LuckPerms
softdepend:
  - PlaceholderAPI
libraries:
  # kyori
  - net.kyori:adventure-api:+
  - net.kyori:adventure-platform-bungeecord:+
  # parsing
  - com.fasterxml.jackson.core:jackson-databind:+
  - com.fasterxml.jackson.datatype:jackson-datatype-jsr310:+
  # database connector
  - javax.persistence:javax.persistence-api:+
  - org.hibernate:hibernate-core:+
  - org.jboss:jandex:+
  - com.zaxxer:HikariCP:+
  # database drivers
  - org.mariadb.jdbc:mariadb-java-client:+
  - com.mysql:mysql-connector-j:+
  - com.h2database:h2:+
  # rabbitmq
  - com.rabbitmq:amqp-client:+
commands:
  reload:
    description: Reloads Configuration Files
    permission: libmod.reload
