name: LibMod
version: '0.1.0'
author: Kaleidox
description: Compatibility Library for AMPZ Minecraft Addons
website: https://github.com/AMPZNetwork/LibMod
main: com.ampznetwork.libmod.spigot.LibMod$Spigot
default-permission: op
api-version: '1.18'
database: true
load: STARTUP
depend:
  - LuckPerms
softdepend:
  - PlaceholderAPI
libraries:
  # kyori
  - 'net.kyori:adventure-api:4.24.0'
  - 'net.kyori:adventure-platform-bungeecord:4.3.4'
  - 'net.kyori:adventure-text-serializer-plain:4.24.0'
  - 'net.kyori:adventure-text-serializer-legacy:4.24.0'
  - 'net.kyori:adventure-text-serializer-json:4.24.0'
  - 'net.kyori:adventure-text-serializer-gson:4.24.0'
  # parsing
  - 'com.google.code.gson:gson:2.11.0'
  - 'com.fasterxml.jackson.core:jackson-databind:2.18.0'
  - 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.0'
  # database connector
  - 'jakarta.persistence:jakarta.persistence-api:2.2'
  - 'org.hibernate:hibernate-core:6.6.0.Final'
  - 'org.jboss:jandex:2.4.5.Final'
  - 'com.zaxxer:HikariCP:4.0.3'
  # database drivers
  - 'org.mariadb.jdbc:mariadb-java-client:3.4.0'
  - 'com.mysql:mysql-connector-j:8.4.0'
  - 'com.h2database:h2:2.2.224'
  # rabbitmq
  - 'com.rabbitmq:amqp-client:5.18.0'
commands:
  reload:
    description: Reloads Configuration Files
    permission: libmod.reload
permissions:
  libmod:
    description: Root Permission Node
    children:
      libmod.reload:
        description: Permission for the /libmod:reload command
        default: op
